services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    image: zwpseudo/hostlife
    container_name: hostlife-web
    restart: unless-stopped
    volumes:
      - hostlife-data:/hostlife/data
      - hostlife-nginx-data:/hostlife/nginx
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=0
    ports:
      - "5000"
    networks:
      - default_network
    command: python run.py

  nginx:
    image: nginx:1.28-alpine
    container_name: hostlife-nginx
    restart: unless-stopped
    volumes:
      - hostlife-nginx-data:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - default_network

networks:
  default_network:
    driver: bridge

volumes:
  hostlife-data:
    external: false
  hostlife-nginx-data:
    external: false