
---
include:
 - docker-compose-traefik.yml
 - docker-compose-authentik.yml

services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    image: zwpseudo/hostlife
    container_name: hostlife-web
    restart: unless-stopped
    volumes:
      - hostlife-data:/hostlife/data
      - hostlife-nginx-data:/hostlife/nginx
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=0
    networks:
      - default_network
    command: python run.py # --traefik-authentik # --registry-lock https://my-private-locked-registry.example

  nginx:
    image: nginx:1.28-alpine
    container_name: hostlife-nginx
    restart: unless-stopped
    volumes:
      - hostlife-nginx-data:/etc/nginx/conf.d
    depends_on:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.hostlife.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.hostlife.entrypoints=websecure
      - traefik.http.routers.hostlife.tls.certresolver=acme-resolver
      - traefik.http.services.hostlife.loadbalancer.server.port=80
      # enable middleware to add authentication by authentik
      # - traefik.http.routers.hostlife.middlewares=authentik@file
      - traefik.docker.network=proxy_network
    networks:
      - default_network
      - proxy_network

networks:
  default_network:
    driver: bridge

volumes:
  hostlife-data:
    external: false
  hostlife-nginx-data:
    external: false